<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [
    <!ELEMENT deportistas (f1*, tenis*)>
    <!ELEMENT f1 (#PCDATA)>
    <!ATTLIST f1 codigo CDATA #REQUIRED>
    <!ATTLIST f1 pais CDATA #IMPLIED>
    <!ELEMENT tenis (#PCDATA)>
]>
<deportistas>
    <f1 codigo="VET" pais="ALE">Sebatastian Vettel</f1>
    <f1 codigo="ALO">Fernando Alonso</f1>
    <f1 codigo="SAI" pais="ESP">Carlos Sainz</f1>
    <tenis>Rafael Nadal</tenis>
</deportistas>
